$(document).ready(function(){
    dialog();
    connexion();
    inscription();
    deconnexion();
    createConference();
    createCategorie();
    getConference();
    refreshGetConference();
    refreshgetConferenceNonVote()
    getConferenceVote();
    getGererConference();
    allConferenceSupprimer();
    getConferenceTop10();
    getGererUser()
})