version: "3.5"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: webdevops/php-nginx:7.3
    working_dir: /app
    ports:
      - 80:80
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - "./sql/projet_v1.sql:/var/lib/mysql"
    ports:
      - "3306:3306"
    expose:
      - "3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: root